[2019-10-03 21:50:09 +0000] [5685] [INFO] Starting gunicorn 19.9.0
[2019-10-03 21:50:09 +0000] [5685] [INFO] Listening at: http://0.0.0.0:5000 (5685)
[2019-10-03 21:50:09 +0000] [5685] [INFO] Using worker: sync
[2019-10-03 21:50:09 +0000] [5689] [INFO] Booting worker with pid: 5689
[2019-10-03 21:50:09 +0000] [5689] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named main
[2019-10-03 21:50:09 +0000] [5689] [INFO] Worker exiting (pid: 5689)
[2019-10-03 21:50:09 +0000] [5685] [INFO] Shutting down: Master
[2019-10-03 21:50:09 +0000] [5685] [INFO] Reason: Worker failed to boot.
